apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: statusquarkusio-38ed
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: statusquarkusio-38ed
    app.kubernetes.io/part-of: status-quarkus-io
  name: statusquarkusio-38ed
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: statusquarkusio-38ed
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: statusquarkusio-38ed
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-izja-tenant/status-quarkus-io/statusquarkusio-38ed@sha256:35a3852d48d53878373ea6867cebbf71b04cf1a2896c5c7cd93f6a5637409317
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 9081
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
