apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: statusquarkusio-38ed
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-izja-tenant/status-quarkus-io/statusquarkusio-38ed@sha256:35a3852d48d53878373ea6867cebbf71b04cf1a2896c5c7cd93f6a5637409317
        name: my-java-quarkus
        resources: {}
status: {}
